sudo: false
dist: trusty
language: python
python:
- '3.5'
env:
  matrix:
  - TOX_ENV=單元試驗
  - TOX_ENV=匯新北市150句閣ppl
  - TOX_ENV=匯常見的語料狀況
  - TOX_ENV=匯TAICORP詞性
  - TOX_ENV=匯詞彙分級
  - TOX_ENV=flake8
install:
- pip install tox
- pip install python-coveralls
branches:
  only:
  - master
script:
- tox -e $TOX_ENV
after_success:
- coverage report
- coveralls
