# Generated by Django 2.0.2 on 2018-05-25 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='語料狀況表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('狀況', models.CharField(max_length=30, unique=True)),
                ('確定會當用', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '狀況表',
                'verbose_name_plural': '狀況表',
            },
        ),
        migrations.CreateModel(
            name='語料表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('原本漢字', models.TextField()),
                ('原本羅馬字', models.TextField()),
                ('漢字', models.TextField()),
                ('羅馬字', models.TextField()),
                ('詞性', models.TextField(blank=True, null=True)),
                ('備註', models.TextField(blank=True)),
                ('標記時間', models.DateTimeField(null=True)),
                ('標記者', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('語料狀況', models.ManyToManyField(blank=True, to='標記.語料狀況表')),
            ],
            options={
                'verbose_name': '語料表',
                'verbose_name_plural': '語料表',
            },
        ),
        migrations.CreateModel(
            name='標記表',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
                'verbose_name': '標記表',
                'verbose_name_plural': '標記表',
            },
            bases=('標記.語料表',),
        ),
        migrations.AlterUniqueTogether(
            name='語料表',
            unique_together={('原本漢字', '原本羅馬字')},
        ),
    ]
