# Generated by Django 2.0.5 on 2018-05-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('標記', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='語料表',
            name='詞性',
            field=models.TextField(blank=True, null=True),
        ),
    ]
