# Generated by Django 2.0.2 on 2018-06-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('標記', '0002_詞性表'),
    ]

    operations = [
        migrations.AddField(
            model_name='語料表',
            name='perplexity',
            field=models.FloatField(default=-99),
        ),
    ]
