# Generated by Django 2.0.2 on 2018-06-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('標記', '0003_語料表_perplexity'),
    ]

    operations = [
        migrations.CreateModel(
            name='基礎句選擇表',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': '基礎句選擇',
                'indexes': [],
                'verbose_name': '基礎句選擇',
            },
            bases=('標記.語料表',),
        ),
        migrations.AddField(
            model_name='語料表',
            name='先標記無',
            field=models.BooleanField(default=False),
        ),
    ]
