# Generated by Django 2.0.6 on 2018-06-26 03:26

from django.db import migrations, models


def _加來源(apps, schema_editor):
    語料表 = apps.get_model("標記", "語料表")
    語料表.objects.filter(pk__lte=150).update(來源='新北市例句')
    語料表.objects.filter(pk__gt=150).update(來源='詞彙分級')


class Migration(migrations.Migration):

    dependencies = [
        ('標記', '0004_auto_20180613_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='語料表',
            name='來源',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(_加來源, lambda *x:x),
        migrations.AlterField(
            model_name='語料表',
            name='來源',
            field=models.TextField(),
        ),
    ]
