# Generated by Django 2.0.6 on 2018-06-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('標記', '0005_語料表_來源'),
    ]

    operations = [
        migrations.AlterField(
            model_name='語料表',
            name='perplexity',
            field=models.FloatField(default=99999),
        ),
    ]
